### PR TITLE
[LEOP-456]: Update packages

### PR DESCRIPTION
**Pull request by jaysonwu991**
## Description

- CRA v4 is out of date and lack of maintenance
- There are some security issues with these low packages
- More engineers are migrating to Mac M1 Pro, there are some issues with `node-sass` v6+

## How you solve it?

- Upgrade the packages in `react-scripts` as many as possible to the latest
 
## Screenshots

image
image
image

### CODE REVIEW

**Comment by paultan2021** [comment]
Please attach any screenshot to prove this works for banana on both build and start

**Comment by paultan2021** [comment]
Also, just a small comment, could you setup a PR template for BRS?

**Comment by jaysonwu991** [comment]
> Also, just a small comment, could you setup a PR template for BRS?

This should be in another PR, this PR won't include this feature.

**Comment by jaysonwu991** [comment]
> Please attach any screenshot to prove this works for banana on both build and start

Will do, please use `Please attach any screenshot to prove it really works on both build and start` these words, not use words includes our internal project name.

**Review by paultan2021 — APPROVED** [review]

**Pull request merged**
