### PR TITLE
[LEOP-23]: Add thread-loader to speed up webpack workflow

### PR DESCRIPTION
**Pull request by jayson991**
## Why

> Bundling JS process takes much time to complete, running in parallels can speed up the whole bundle workflow.

## Changes

- [x] Add `thread-loader` to `webpack.config.js`
- [x] Add `thread-loader` to `webpack.config.ssr.js` but comment that out not to use

## Impact

- [x] Development
- [x] Production

## Positive Impact From Experiments

- [Webpack v4 Optimization Experimental Data](https://confluence.skyscannertools.net/display/LEOP/Webpack+v4+Optimization+Experimental+Data)

## Something Wired

> For bundling CSS, using `thread-loader` breaks down `postcss-loader`, I have tried a lot of ways to make `postcss-loader` work normally, but it just fails, So this PR is just for bundling JS.

### CODE REVIEW

**Review by olliecurtis — CHANGES_REQUESTED** [review]
Could you add and entry to CHANGELOG?

**Review by olliecurtis — CHANGES_REQUESTED** [review]
Can you double check the changes here at it seems that it wants to change 33 files instead of 3 places it wants to touch. 

Might just require a rebase on this branch in order to fix it up

**Comment by jayson991** [comment]
> Could you add and entry to CHANGELOG?

Yeah, Have added it.

**Comment by jayson991** [comment]
> Can you double check the changes here at it seems that it wants to change 33 files instead of 3 places it wants to touch.
> 
> Might just require a rebase on this branch in order to fix it up

Have fixed the changes, but I think there will be conflicts if [https://github.com/Skyscanner/backpack-react-scripts/pull/92](https://github.com/Skyscanner/backpack-react-scripts/pull/92) is merged to `fork` branch first and it should be anyway.

**Pull request merged**
