### PR TITLE
[LEOP-274]: Sync backpack-react-script beta version into default branch

### PR DESCRIPTION
**Pull request by SophiaChen2021**
Acorn uses backpack-react-script 9.4.0-beta.5 , Hotels Website uses 9.5.0-beta.1,   they all released from branch no-jira-brs-9-full-ssr-hard-source, 

there is a pending pr(#95) waiting for merge code from branch no-jira-brs-9-full-ssr-hard-source to default(that is fork) branch

### CODE REVIEW

**Comment by michael-booth** [comment]
One comment - have we made on whether this will be released as a major or minor version?
i..e will the change in build directory structure happen regardless of whether the user is using SSR or CSR (making it a breaking change)
Or will it only change if SSR is opted into (making it a minor change).

@jaysonwu991 given you are looking to potentially do some work to update sass-loader to the same version as CRA (10.x) and that this may bring in performance benefits we should be careful either that is blocked behind a new major version or if it would potentially go in as part of a 9.x release. 

It might be good to think about the roadmap of things we want to deliver in the short/medium term and work out the best order for those to be delivered.

**Comment by jaysonwu991** [comment]
Thanks @michael-booth, this PR is just to merge SSR feature to `fork` branch, and it won't do extra actions as the roadmap lists.

Once this PR is merged, there should be a minor version to test just SSR on CI because projects like `hotels-website` and `acorn` are just doing that like this.

Once [Build Path(s) PR](https://github.com/Skyscanner/backpack-react-scripts/pull/109) is merged, will release a major version with `Webpack` 4 (The limitation from `Webpack` 4 is the reason that sass-loader just upgrades to 10.x, and there seems no breaking changes for 10.x --> 12.x), and this major version will need to be tested on both CSR and SSR to make sure there are no breaking changes for projects' running. And note that upgrading BRS with `Webpack` 5 won't complete at once, this major version still can bring the benefits of fast bundling.

**Comment by michael-booth** [comment]
@jaysonwu991 thanks for the reply, i'm not sure i follow can you help me understand.

For clarity my understanding is:
This PR:
* Is introducing the SSR feature to the fork branch.
* This will mean if used to build (SSR or CSR) the build folder changes from `build` -> `build/web` / `build/ssr`
* You mentioned "once this PR is merge, there should be am minor version to test just SSR on CI` - do you mean a beta release of the branch to test, or do you mean a new minor version (9.5.0?). I ask because as soon as a new minor version is released like 9.5.0 Skyscanner repos will start getting automated PR's to update.
* If the above points are correct - this sounds like a breaking change rather than a minor.

Build Path(s) PR:
* I'm not clear on the purpose of this PR - is it essentially to make the folder structure change only apply when using SSR, and all other builds (CSR) will continue to just output to the `build` folder?
* If so, is it necessary to do this as 2 PR's, or would it be better to merge those changes into this PR first?
* Assuming all the above is correct this would mean SSR feature could be released as a new minor version as it is "opt in" for those that want to use it?

To the point about updating sass-loader - my was slightly incorrect in my previous statement.
I meant to say, it maybe desirable for us to update sass-loader to version 10.x (as is used in CRA 4.x) as this provides potential performance benefits and helps us move towards BRS for all sass compilation while still being a minor version release.
My only concern was if this was merged and required a major version. The benefit of the newer sass-loader would be dependent on teams performing the migration to BRS 10.x instead of just merging a minor version.

**Comment by olliecurtis** [comment]
@michael-booth - I might be able to answer some of your quesitons here

>Is introducing the SSR feature to the fork branch.

No SSR already exists on the fork branch and has been since BRS inception - this builds on further SSR improvements and loadable component support to the SSR build so an improvement

> This will mean if used to build (SSR or CSR) the build folder changes from build -> build/web / build/ssr

Yes with these new changes they are now more separated out into folders instead of being bundled into one location - this helps with the local development and have the hot reloading functionality working to automatically rebuild ssr code when it changes - instead of the old way of needing to stop the development system and then rebuild, then restart

> Build Path(s) PR:

Just took a look at this PR myself and if that feature goes in I would maybe combine it in this PR as that build path will be breaking for people currently using SSR - as projects in Skyscanner are using SSR just not in the way Acorn and hotels are so if those projects want to keep using SSR - then need to 'opt-in' which requires squads to change code to add the config value to enable SSR so would be breaking instead of just approving and merging a minor version as it would then break functionality they were expecting.

c.c. @jaysonwu991 

>To the point about updating sass-loader - my was slightly incorrect in my previous statement.
>I meant to say, it maybe desirable for us to update sass-loader to version 10.x (as is used in CRA 4.x) as this provides potential performance benefits and helps us move towards BRS for all sass compilation while still being a minor version release.
>My only concern was if this was merged and required a major version. The benefit of the newer sass-loader would be dependent on teams performing the migration to BRS 10.x instead of just merging a minor version.

I think this can still be a minor version or even a patch! As its just bumping a dependency and wouldn't have any requirement for teams to do work their side as its all still in the tool. Providing we make the right changes to that sassFunctions part - which was the blocker previously but looks like we have a way through it now - I wouldn't see it as a breaking change for us to bump this as it doesn't look to change sass functionality for folks

**Comment by michael-booth** [comment]
Thanks @olliecurtis thanks for the reply I think that clarifies my questions.

Totally agree sass-loader update should just be a minor/patch version at most 👍

**Comment by jaysonwu991** [comment]
@olliecurtis Thanks very much for helping me answer @michael-booth 's questions, all makes sense to me.

Agree with @michael-booth , these 2 PRs about `SSR` should be `opt-in` for the Web, and the feature of sass-loader (v8.0.0+) with `UV_THREADPOOL_SIZE` environment variable should be released in 9.x of BRS.

**Comment by jaysonwu991** [comment]
## Roadmap For sass-loader With UV_THREADPOOL_SIZE environment variable

1. Create a new branch from `fork` branch
2. In this new branch install sass-loader v10.2.1
3. Move `functions` field into sassOptions to configure sass-loader
4. Compare BNS+(Import .css)+BRS with (Import .sass)+BRS(With UV_THREADPOOL_SIZE=x)
5. Determine if BNS should be deprecated or not (Only BRS will be better)
6. Merge the PR created by this new branch into `fork` branch
7. Release BRS v9.5.0
8. Announce this new version to the Web

## Roadmap for SSR

1. Remove `hard-source-webpack-plugin` from SSR feature branch (#107)
2. Make build path(s) compatible for both CSR and SSR (#109)
3. Merge #109 into #107
4. Publish a beta version from #107 
5. Test beta version in Acorn
6. All is well, then merge #107 into `fork` branch
7. Release v9.6.0

**Comment by jaysonwu991** [comment]
Have implemented in #109.

**Pull request closed without merging**
