### PR TITLE
[Draft] Renaming chunks to invalidate CDN cache

### PR DESCRIPTION
**Pull request by AnushreeBagchi**
We recently had an [incident](https://gojira.skyscanner.net/browse/INL-1474) in Banana due to CDN having empty chunks in its cache. To mitigate this issue we decided to rename all our chunks and invalidate existing chunks in CDN.

This PR is adding a string from package.json to the chunk name after the content hash. In the future, if we want to rename the chunks again, we will have to update the text in the package.json file.

### CODE REVIEW

**Review by runmoore — CHANGES_REQUESTED** [review]
A few things to add @AnushreeBagchi 

1. Can you add tests
2. Can you add documentation

We're adding new functionality here, but there's no documentation or even testing to indicate how this should work and why it might be needed. Since BRS is a the foundation of web at skyscanner, and is a fork of an open source project. We need a higher standard of documentation than we might normally have in other code.

Until this is added we aren't able to proceed to review this PR.

**Comment by AnushreeBagchi** [comment]
> ere's no documentation or even testing to indicate how this

Hi Chris. Thanks for the comment. Will add tests and documentation for this if we decide to accept this approach :)

**Comment by mungodewar** [comment]
Q: Will you need to also change `filename` config? Given that this main file may async load in other (cached) assets you'll probably want to bust that file too, right?

**Comment by mungodewar** [comment]
IIRC Leopard spent a lot of time isolating bpk only changes from the rest of react-scripts. I think that abstraction lives in: https://github.com/Skyscanner/backpack-react-scripts/tree/fork/packages/react-scripts/backpack-addons can we align to that pattern too?

**Comment by olliecurtis** [comment]
Spoken to @AnushreeBagchi about this and this PR can safely be closed :)

**Pull request closed without merging**
